tags:
  - name: Productos
    description: Operaciones relacionadas con productos
paths:
  /api/products:
    get:
      tags:
        - Productos
      summary: Obtiene todos los productos
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Número máximo de productos a retornar
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número de página actual
        - in: query
          name: query
          schema:
            type: string
            default: '{}'
          description: "Filtros de búsqueda en formato JSON (ejemplo: {'category': 'example', 'status': 1})"
        - in: query
          name: sort
          schema:
            type: string
            default: null
          description: Orden de clasificación de los productos
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  totalPages:
                    type: integer
                  prevPage:
                    type: integer
                  nextPage:
                    type: integer
                  page:
                    type: integer
                  hasPrevPage:
                    type: boolean
                  hasNextPage:
                    type: boolean
                  prevLink:
                    type: string
                  nextLink:
                    type: string
    post:
      tags:
        - Productos
      summary: Crea un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error de solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/products/{id}:
    get:
      tags:
        - Productos
      summary: Obtiene un producto por ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del producto a buscar
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Productos
      summary: Actualiza un producto por ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del producto a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProduct'
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Error de solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Productos
      summary: Elimina un producto por ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del producto a eliminar
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Error de solicitud
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Usuario no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'